spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update     # or create / create-drop / validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

pricing:
  binance:
    base-url: https://api.binance.com/
    api-version: api/v3/
    price-endpoint: ticker/bookTicker
  huobi:
    base-url: https://api.huobi.pro/
    price-endpoint: market/tickers

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.trade.pricing: INFO
