server:
  port: 8081

spring:
  application:
    name: cron-pricing
  
  main:
    allow-bean-definition-overriding: true
    
  datasource:
    url: jdbc:h2:file:./data/tradedb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
  
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: PricingScheduler
          threadPool:
            threadCount: 5

pricing:
  binance:
    base-url: https://api.binance.com/
    api-version: api/v3/
    price-endpoint: ticker/bookTicker
  huobi:
    base-url: https://api.huobi.pro/
    price-endpoint: market/tickers

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.trade.pricing: INFO
    org.quartz: INFO
